
# General

# Jobs
NEW_JOB_WAIT_PERIOD_SECONDS=120
JOB_CONTAINERS_PER_INSTANCE=2

# JobItems
NEW_JOB_ITEM_WAIT_PERIOD_SECONDS=120
JOB_ITEM_CONTAINERS_PER_INSTANCE=2

# EC2 Autoscaling
MIN_JOB_INSTANCES=0
MAX_JOB_INSTANCES=1
MIN_JOB_ITEM_INSTANCES=0
MAX_JOB_ITEM_INSTANCES=3

# ECS Container Service 
MIN_JOB_CONTAINERS=0
MAX_JOB_CONTAINERS=1
MIN_JOB_ITEM_CONTAINERS=0
MAX_JOB_ITEM_CONTAINERS=3