from bigneuron_app import config

LOG_LEVEL=config.APP_LOG_LEVEL
MAIL_LOG_LEVEL=config.MAIL_LOG_LEVEL
LOG_FILE_PATH='logs/'
LOG_INTERVAL_TYPE='D'
LOG_BACKUP_INCR=10
LOG_INTERVAL=1

JOB_ITEMS_LOG_FILE= LOG_FILE_PATH + 'JobItems.log'
JOBS_LOG_FILE= LOG_FILE_PATH + 'Jobs.log'
TASKS_LOG_FILE= LOG_FILE_PATH + 'Tasks.log'
APP_LOG_FILE= LOG_FILE_PATH + 'app.log'